# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
  development:
    adapter: postgresql
    encoding: unicode
    database: RR05_development
    pool: 5
    username: admin
    password: 123456
  test:
    adapter: postgresql
    encoding: unicode
    database: RR05_test
    pool: 5
    username: admin
    password: 123456
  production:
    adapter: postgresql
    encoding: unicode
    database: RR05_production
    pool: 5
    username: admin
    password: 123456
